### ISSUE TITLE
Valid Variable Names

### ISSUE THREAD

**Issue by hobbesdaboba** [EnricSala/influxdb-matlab#1]
Thanks for this library! It saved me quite a bit of time. 👍 
Sometimes the variable names coming from influxdb aren't valid matlab table names. For example, tags that have * or - will cause result.series().table() and timetable() to crash in 2017b.

An easy fix is just to call genvarname on obj.Fields:
```
result = table(obj.Values{:}, 'VariableNames', genvarname(obj.Fields));
result = timetable(time, obj.Values{:}, 'VariableNames', genvarname(obj.Fields));
```

Cheers!

**Comment by EnricSala** [comment]
@hobbesdaboba I'm glad you found this library useful :)

Regarding the special characters in variable names, I was hoping no one would use them haha. But they are valid in InfluxDB, so I added your fix. Thanks for the tip about `genvarnames`!
