### ISSUE TITLE
How to close it 

### ISSUE THREAD

**Issue by Catheriana2** [EnricSala/influxdb-matlab#15]
There exists the sentence like "close(conn)" in Python for Influxdb. How can I close the connection of Influxdb in matlab in oreder to prevent some problems such as memory leak.

Thank you very much.

**Comment by EnricSala** [comment]
Hi @Catheriana2,

This client implementation does not keep any resources open, so there is nothing to close.

It is safe to create as many instances as needed, it will not leak any resources.

Closing this issue as resolved. Feel free to reopen it or create a different issue if necessary :)

**Comment by Catheriana** [comment]
Thank you very much~!
