### ISSUE TITLE
Problem with Matlab Compiler

### ISSUE THREAD

**Issue by GeriReichl** [EnricSala/influxdb-matlab#16]
Hi all! 

I face a problem with the series-builder to write data into the influx db after compiling the Matlab code. 

**Undefined function 'urlencode' for input arguments of type 'char'**

Did someone of you have the same problem?

Thank you very much

**Comment by EnricSala** [comment]
Hi @GeriReichl,

I haven't tried to use the library with compiled code, not sure what the limitations would be.

Does Matlab allow specifying which toolboxes or functions to support/include when compiling the code? I'm not sure, would suggest looking into that. The Matlab forums might also be a good place to ask this question.

Thanks for reporting the finding :)

**Comment by GeriReichl** [comment]
Hi @EnricSala,

I solved the problem by adding the following simple function to the repository.

`function urlOut = urldecode(urlIn)
   urlOut = char(java.net.URLDecoder.decode(urlIn,'UTF-8'));
end
`

The Matlab-inculded function urldecode is not supported by the Matlab Compiler.

kind regards and thank you
