### ISSUE TITLE
Streaming data to matlab

### ISSUE THREAD

**Issue by Kamehaha** [EnricSala/influxdb-matlab#6]
Hi,

I managed to retrieve the data from influxdb. But is not streaming the data, is there a way to stream the data? (I'm streaming data into influxdb in 1000 Hz and at the same time would like to stream it to matlab as if is 'real time') Is this possible? Thanks is advance ya

**Comment by EnricSala** [comment]
Hi @Kamehaha, 
No, this library does not support streaming data. You may be able to do something similar by continuously requesting time windows using a loop.
